############################
## CHANGE THESE
############################

baseURL: 'https://SizhuangHe.github.io/template'
title: template

############################
## MISC
############################

enableEmoji: true
disableKinds: ['taxonomy', 'term']
languageCode: 'en-us'


